package validation;

import SSE.InstantaneousRateMatrix;
import SSE.StateDependentSpeciationExtinctionProcess;
import SSE.TraitStash;
import beast.base.evolution.alignment.Taxon;
import beast.base.evolution.alignment.TaxonSet;
import beast.base.evolution.tree.TreeParser;
import beast.base.inference.parameter.RealParameter;
import test.TestHelper;

import java.util.Arrays;
import java.util.List;

/** Generates the SSE ancestral-state samples used by the BiSSE validation workflow. */
public class SDSEPValidationBiSSEASR {
    static final double EPSILON = 1e-2;
    static final int numTrials = 10000;

    int numTimeSlices = 100;
    private StateDependentSpeciationExtinctionProcess sdsep;

    /** Runs the validation data set and writes its joint and stochastic summaries. */
    public static void main(String[] args) throws Exception {
        SDSEPValidationBiSSEASR makeCSVs = new SDSEPValidationBiSSEASR();
        String pathToWriteIn = args[0];
        makeCSVs.runRb(pathToWriteIn);
    }

    /** Builds a BiSSE model and writes samples from both ancestral-state reconstruction methods. */
    public void runExperiment(String treeStr, String spAttr, String[] spNames, String expName,
                              Double[] lambdas, Double[] mus, Double[] pis, String q,
                              int numberOfTimeSlices) throws Exception {
        int numberOfStates = 2;
        List<Taxon> taxaList = Taxon.createTaxonList(Arrays.asList(spNames));
        TaxonSet taxonSet = new TaxonSet(taxaList);

        TraitStash traitStash = new TraitStash();
        traitStash.initByName("numberOfStates", numberOfStates, "taxa", taxonSet, "value", spAttr);

        RealParameter lambda = new RealParameter(lambdas);
        RealParameter mu = new RealParameter(mus);
        RealParameter pi = new RealParameter(pis);

        InstantaneousRateMatrix irm = new InstantaneousRateMatrix();
        irm.initByName("numberOfStates", numberOfStates, "flatQMatrix", q);

        System.out.println("Lambdas: " + Arrays.toString(lambdas));
        System.out.println("Mus: " + Arrays.toString(mus));
        System.out.println("Pis: " + Arrays.toString(pis));
        System.out.println("Qs:");
        irm.printMatrix();

        TreeParser myTree = new TreeParser(treeStr, false, false, true, 0);
        boolean incorporateCladogenesis = false;

        sdsep = new StateDependentSpeciationExtinctionProcess();
        sdsep.initByName(
                "tree", myTree,
                "traitStash", traitStash,
                "instantaneousRateMatrix", irm,
                "lambda", lambda,
                "mu", mu,
                "pi", pi,
                "incorporateCladogenesis", incorporateCladogenesis);

        sdsep.setNumTimeSlices(numberOfTimeSlices);
        double[] posteriorStoc = sdsep.sampleAndSummarizeBiSSE(numTrials, false);
        double[] posteriorJoint = sdsep.sampleAndSummarizeBiSSE(numTrials, true);
        System.out.println(Arrays.toString(sdsep.getNodeIndexNameMapper()));

        TestHelper.prepareAndWriteToCSV(posteriorJoint, expName + "SSE_asr_joint", sdsep);
        TestHelper.prepareAndWriteToCSV(posteriorStoc, expName + "SSE_asr_stoc", sdsep);
    }

    /** Supplies the fixed data set generated by prepare_BiSSE_ASR_input.R. */
    public void runRb(String pathToWriteIn) throws Exception {
        String treeStr = "(((sp15:0.5701922606,(sp22:0.1174274481,sp23:0.1174274481)nd22:0.4527648125)nd6:5.46955786,((sp4:2.913008462,(sp16:0.4790358056,sp17:0.4790358056)nd11:2.433972656)nd9:1.72680138,sp2:4.639809842)nd7:1.399940278)nd2:8.039087646,((sp1:5.262858931,((((sp10:1.936988093,sp11:1.936988093)nd15:0.8700699862,((sp20:0.1813602217,sp21:0.1813602217)nd17:2.59756285,sp6:2.778923072)nd16:0.02813500652)nd12:0.1038009358,(sp14:1.103215563,(sp18:0.2976700868,sp19:0.2976700868)nd21:0.805545476)nd13:1.807643452)nd10:0.5229591127,sp3:3.433818127)nd8:1.829040804)nd4:1.760591904,((((sp8:1.951198056,sp9:1.951198056)nd20:0.153294648,sp7:2.104492704)nd18:0.5588707339,sp12:2.663363438)nd14:0.2401874525,sp5:2.90355089)nd5:4.119899945)nd3:7.055386931)nd1;";
        String spAttr = "sp1=1,sp2=1,sp3=1,sp4=2,sp5=1,sp6=1,sp7=2,sp8=1,sp9=1,sp10=1,sp11=1,sp12=1,sp14=1,sp15=2,sp16=2,sp17=1,sp18=1,sp19=1,sp20=2,sp21=2,sp22=1,sp23=1";
        String[] spNames = {
                "sp1", "sp2", "sp3", "sp4", "sp5", "sp6", "sp7", "sp8", "sp9", "sp10", "sp11",
                "sp12", "sp14", "sp15", "sp16", "sp17", "sp18", "sp19", "sp20", "sp21", "sp22", "sp23"
        };
        Double[] lambdas = {0.2, 0.4};
        Double[] mus = {0.001, 0.1};
        Double[] pis = {0.0, 0.0, 0.5, 0.5};
        String q = "0.1 0.4";

        runExperiment(treeStr, spAttr, spNames, pathToWriteIn, lambdas, mus, pis, q, numTimeSlices);
    }
}
