// Fourier transforms for SSE.fft.FftwFFT, separate from the retained MoSSE library.
// Java input -> reusable native input -> FFTW -> existing Java output.
// Complex transforms preserve Java's alternating real/imaginary layout. Convolution,
// boundaries and time integration remain in Java. JNI declarations are generated by javac -h.
#include "SSE_fft_FftwFFT.h"

#include "native_support.h"

using namespace quasse_native;

// Only Java's private native methods exchange these pointers, and its cleanup-state lock owns lifetime.
JNIEXPORT jlong JNICALL Java_SSE_fft_FftwFFT_create(JNIEnv* env, jclass, jint size) {
    if (size <= 0 || size > std::numeric_limits<jint>::max() / 2
            || static_cast<std::size_t>(size) > std::numeric_limits<std::size_t>::max() / sizeof(fftw_complex)) {
        throw_java(env, "java/lang/IllegalArgumentException", "FFT size must be positive and 2*N must fit in an int.");
        return 0;
    }
    try {
        std::lock_guard lock(preparation_mutex);
        return static_cast<jlong>(reinterpret_cast<std::intptr_t>(new ComplexFFT(size)));
    } catch (...) {
        translate_exception(env);
        return 0;
    }
}

// Validate before copying; reuse native arrays and write directly into the caller's existing output.
JNIEXPORT void JNICALL Java_SSE_fft_FftwFFT_execute(JNIEnv* env, jclass, jlong handle,
                                               jdoubleArray input, jdoubleArray output, jboolean inverse) {
    try {
        auto* fft = reinterpret_cast<ComplexFFT*>(static_cast<std::intptr_t>(handle));
        if (!fft) {
            throw_java(env, "java/lang/IllegalStateException", "FFT has been closed.");
            return;
        }
        if (!input || !output || env->GetArrayLength(input) != 2 * fft->size
                || env->GetArrayLength(output) != 2 * fft->size || env->IsSameObject(input, output)) {
            throw_java(env, "java/lang/IllegalArgumentException", "FFT requires distinct arrays of 2*N doubles.");
            return;
        }
        env->GetDoubleArrayRegion(input, 0, 2 * fft->size, reinterpret_cast<double*>(fft->input.get()));
        if (env->ExceptionCheck()) return;
        fft->transform(inverse);
        env->SetDoubleArrayRegion(output, 0, 2 * fft->size, reinterpret_cast<double*>(fft->output.get()));
    } catch (...) {
        translate_exception(env);
    }
}

// Java serializes this with execution; the native lock also excludes other instances' preparation.
JNIEXPORT void JNICALL Java_SSE_fft_FftwFFT_destroy(JNIEnv* env, jclass, jlong handle) {
    try {
        std::lock_guard lock(preparation_mutex);
        delete reinterpret_cast<ComplexFFT*>(static_cast<std::intptr_t>(handle));
    } catch (...) {
        translate_exception(env);
    }
}
